version: '3'
services:
  master:
    build: jenkins-master
    tty: true
    privileged: true
    volumes:
      - "./backup:/backup"
      - "./jenkins_homes:/var/lib/jenkins"
      - "./jenkins-master/build/plugins:/var/lib/jenkins/plugins"
      - "./jenkins-master/build/jobs:/var/lib/jenkins/jobs"
      - "./jenkins-master/build/test:/var/lib/jenkins/jobs/hello-dropwizard/workspace/src/test"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "/usr/bin/docker:/usr/bin/docker"
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      default_net:
       ipv4_address: 172.28.1.4

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      default_net:
       ipv4_address: 172.28.1.2
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - "./sonarqube_conf:/opt/sonarqube/conf"
      - "./sonarqube_data:/opt/sonarqube/data"
      - "./sonarqube_extensions:/opt/sonarqube/extensions"
      - "./sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins"


  db:
    image: postgres
    networks:
      - default
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    networks:
      default_net:
       ipv4_address: 172.28.1.5
    volumes:
      - "./postgresql:/var/lib/postgresql"
      - "./postgresql_data:/var/lib/postgresql/data"


  registry:
    restart: always
    image: registry:2
    ports:
      - "5000:5000"
    networks:
      default_net:
       ipv4_address: 172.28.1.3
    volumes:
      - "./registry/data:/var/lib/registry"
networks:
    default_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16